services:
  
  rabbitmq:
    image: rabbitmq:3.9-management
    ports: 
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  
  zipkin:
    image: openzipkin/zipkin
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports: 
      - 9411:9411
    environment: 
      SPRING_RABBITMQ_HOST: rabbitmq

  eureka-server:
    build: ./eureka-server/
    image: eureka-server
    ports: 
      - 8761:8761
    depends_on:
      rabbitmq:
        condition: service_healthy
    
    
  spring-cloud-config-server:
    build: ./spring-cloud-config-server/
    image: spring-cloud-config-server
    ports: 
      - 8888:8888
    depends_on:
      - eureka-server

  currency-exchanges-service:
    build: ./currency-exchanges-service/
    image: currency-exchanges-service
    ports: 
      - 8000:8000
    depends_on:
      - spring-cloud-config-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  currency-conversions-service:
    build: ./currency-conversions-service/
    image: currency-conversions-service
    ports: 
      - 8100:8100
    depends_on:
      - spring-cloud-config-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  zuul-server:
    build: ./zuul-server/
    image: zuul-server
    ports: 
      - 8765:8765
    depends_on:
      - currency-exchanges-service
      - currency-conversions-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      
