services:
  
  rabbitmq:
    image: rabbitmq:3.9-management
    ports: 
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
  
  zipkin:
    image: openzipkin/zipkin
    depends_on:
      - rabbitmq
    ports: 
      - 9411:9411
    # environment: 
    #   - RABBIT_URI=amqp://localhost
    links: 
      - rabbitmq

  eureka-server:
    build: ./eureka-server/
    image: eureka-server
    ports: 
      - 8761:8761
    depends_on:
      - rabbitmq
    
  zuul-server:
    build: ./zuul-server/
    image: zuul-server
    ports: 
      - 8765:8765
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  spring-cloud-config-server:
    build: ./spring-cloud-config-server/
    image: spring-cloud-config-server
    ports: 
      - 8888:8888
    depends_on:
      - eureka-server

  currency-exchanges-service:
    build: ./currency-exchanges-service/
    image: currency-exchanges-service
    ports: 
      - 8000:8000
    depends_on:
      - spring-cloud-config-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  currency-conversions-service:
    build: ./currency-conversions-service/
    image: currency-conversions-service
    ports: 
      - 8100:8100
    depends_on:
      - currency-exchanges-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka