spring:
  application:
    name: currency-exchanges-service
  # cloud:
  #   config:
  #     uri: http://localhost:8888
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:h2:mem:exchange-values
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    '[org.springframework]': error

server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: "${spring.application.name}:${server.port}"
    
