spring:
  application:
    name: currency-conversions-service
  cloud:
    loadbalancer:
      ribbon:
        enable: true
        
  config:
    import: "optional:configserver:"

logging:
  level:
    '[org.springframework]': error

server:
  port: 8100

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: "${spring.application.name}:${server.port}"
      