spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:\workspace\udemy\java_spring_boot_microservices_udemy_section5\config-repo\

server:
  port: 8888